package com.clover.spring.datajpa.model;
// default package
// Generated 8 May, 2020 2:48:47 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Loan generated by hbm2java
 */
@Entity
@Table(name = "loan", catalog = "sys")
public class Loan implements java.io.Serializable {

	private Integer loanid;
	private Integer amount;
	
	
	//@Size(min=2, message="Name should have atleast 2 characters")
	@NotEmpty(message = "Name may not be empty")
	private String loanName;
	private Date sanctionDate;
	private Date modifiedDate;

	public Loan() {
	}

	public Loan(Integer amount, String loanName, Date sanctionDate, Date modifiedDate) {
		this.amount = amount;
		this.loanName = loanName;
		this.sanctionDate = sanctionDate;
		this.modifiedDate = modifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "loanid", unique = true, nullable = false)
	public Integer getLoanid() {
		return this.loanid;
	}

	public void setLoanid(Integer loanid) {
		this.loanid = loanid;
	}

	@Column(name = "amount")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@Column(name = "loan_name", length = 25)
	public String getLoanName() {
		return this.loanName;
	}

	public void setLoanName(String loanName) {
		this.loanName = loanName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sanction_date", length = 10)
	public Date getSanctionDate() {
		return this.sanctionDate;
	}

	public void setSanctionDate(Date sanctionDate) {
		this.sanctionDate = sanctionDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_date", length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
